version: '3.8'

services:
  frontend:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - backend
    command: ["npm", "start"]  # Ensures the frontend server starts in development mode
 
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_USER: your_db_user
      DB_HOST: db
      DB_NAME: your_db_name
      DB_PASSWORD: your_db_password
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
